#!/bin/bash
set -e

# Trap signals for graceful shutdown
trap 'echo "Received signal, shutting down..."; kill $(jobs -p); exit 0' SIGTERM SIGINT

# Create appuser profile with environment variables needed for scripts
echo "Setting up appuser environment..."
cat > /home/appuser/.profile << EOF
# Environment variables for appuser (autogenerated at container start)
export BOT_TOKEN="${BOT_TOKEN}"
export CHAT_ID="${CHAT_ID}"
export REGISTRY_NODE_NAME="${REGISTRY_NODE_NAME}"
export POSTGRES_HOST="${POSTGRES_HOST:-postgres_registry}"
export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
export POSTGRES_USER="${POSTGRES_USER:-registry}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-registry}"
export POSTGRES_DB="${POSTGRES_DB:-registry}"
export FILES_DIR="${FILES_DIR:-/files}"
export LOG_DIR="${LOG_DIR:-/var/log/registry}"
export MAX_LOG_FILES="${MAX_LOG_FILES:-7}"
export MAX_MAINTENANCE_LOG_FILES="${MAX_MAINTENANCE_LOG_FILES:-7}"
export MAX_CSV_FILES="${MAX_CSV_FILES:-7}"
export AUTO_EMBED="${AUTO_EMBED:-1}"
export SEMANTIC_URL="${SEMANTIC_URL:-http://semantic:8010/semantic_normalize}"
export TZ="${TZ:-UTC}"
EOF

# Generate crontab from environment variables (run as root, execute as appuser)
echo "Generating crontab from environment..."
cat > /etc/crontabs/root << CRON_EOF
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
${CRON_IMPORT_SCHEDULE:-5 0 * * *} su -l appuser -c "/scripts/run_import.sh" >> /var/log/cron.log 2>&1
${CRON_MAINTENANCE_SCHEDULE:-0 5 * * *} su -l appuser -c "/scripts/run_pg_maintenance.sh" >> /var/log/cron.log 2>&1
CRON_EOF

# Run initial import in background as appuser
echo "Starting initial import..."
su -l appuser -c "/scripts/run_import.sh" &
IMPORT_PID=$!
IMPORT_COMPLETED=false

# Start cron in background (Alpine uses busybox crond)
echo "Starting cron service..."
crond -f -l 2 -L /var/log/cron.log &
CRON_PID=$!

# Function to check if background processes are still running
check_processes() {
    if [ -n "$IMPORT_PID" ] && ! kill -0 $IMPORT_PID 2>/dev/null; then
        if [ "$IMPORT_COMPLETED" = "false" ]; then
            echo "Import process has completed"
            IMPORT_COMPLETED=true
        fi
        IMPORT_PID=""
    fi

    if ! kill -0 $CRON_PID 2>/dev/null; then
        echo "Cron process has died, exiting..."
        exit 1
    fi
}

# Monitor processes and tail logs
echo "Monitoring logs..."
tail -f /var/log/cron.log &
TAIL_PID=$!

# Wait for processes
while [ -n "$IMPORT_PID" ] || kill -0 $CRON_PID 2>/dev/null; do
    check_processes
    sleep 5
done

# Cleanup
kill $TAIL_PID 2>/dev/null || true
echo "All processes completed, shutting down..."
